@token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2FvQGdtYWlsLmNvbSIsImlhdCI6MTY0MTc2MzI5OSwiZXhwIjoxNjQyMzY4MDk5fQ.ikNJ_FmS6N58v1HsT1bT5tWk037URSqOPhW9shPTT6o"

### Home - Index

GET http://localhost:3001

### Users - Store

POST http://localhost:3001/users
Content-Type: application/json

{
  "nome": "joão",
  "password": "123456",
  "email": "joao@gmail.com"
}

### Users - Store

GET http://localhost:3001/users

### Users - Show

GET http://localhost:3001/users/1
Authorization: {{token}}

### Users - Update

PUT http://localhost:3001/users/1
Content-Type: application/json
Authorization: {{token}}

{
  "nome": "joão",
  "password": "123456",
  "email": "joao.teste@gmail.com"
}

### Users - Delete

DELETE http://localhost:3001/users/1
Authorization: {{token}}

### Tokens - Store

POST http://localhost:3001/tokens
Content-Type: application/json

{
  "email": "joao.teste@gmail.com"
}

### Alunos = Index

GET http://localhost:3001/alunos
